# Generated by Django 4.0.1 on 2022-01-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('pkey', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
