# Generated by Django 4.0.1 on 2022-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled', max_length=64),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
