# Generated by Django 4.0.1 on 2022-01-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_quillpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='json_content',
            field=models.CharField(default='', max_length=64),
        ),
    ]
