# Generated by Django 4.0.1 on 2022-01-27 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_json_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=64)),
                ('content', models.CharField(max_length=64)),
                ('json_content', models.CharField(default='', max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
