# Generated by Django 4.0.1 on 2022-02-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_deleted_delete_deletednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.CharField(default=False, max_length=64),
        ),
    ]
